require 'robot_arm'
robot_arm:random_level(1)
robot_arm.speed = 0.9

robot_arm:grab()
robot_arm:move_right()
robot_arm:drop()
robot_arm:move_left()
robot_arm:grab()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:drop()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:grab()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:drop()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:grab()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:drop()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()